/**
 * Real drop-off facilities from OpenStreetMap via the Overpass API.
 *
 * Every field returned here comes from OSM tags or is computed from OSM
 * coordinates. Nothing is generated by a language model, and nothing is
 * guessed: a facility with no `name` tag is described by what its tags say it
 * is, and absent fields (phone, hours, address) are simply omitted rather than
 * filled in. Overpass needs no API key.
 */

const ENDPOINTS = [
  "https://overpass-api.de/api/interpreter",
  "https://overpass.kumi.systems/api/interpreter",
];

// Two attempts at most. The first is small enough that a dense city can't push
// the nearest sites past the element cap; the second is as far as anyone would
// reasonably travel to drop something off. Overpass is a shared free service,
// so keeping the request count low matters as much as the result.
const RADII_M = [5000, 25000];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * Small in-process cache.
 *
 * Overpass is free, shared and slot-limited: hammering it gets you HTTP 429 and
 * wildly variable latency. Facility data barely changes, and repeat lookups from
 * the same neighbourhood are the common case, so a short TTL removes most of
 * the traffic. Keyed on coordinates rounded to ~1km.
 */
const CACHE_TTL_MS = Number(process.env.OVERPASS_CACHE_TTL_MS ?? 10 * 60 * 1000);
const CACHE_MAX = 200;
const cache = new Map();

const cacheKey = (origin, material, hazardous) =>
  `${origin.lat.toFixed(2)},${origin.lon.toFixed(2)}|${material ?? "any"}|${hazardous ? "haz" : "std"}`;

function cacheGet(key) {
  const hit = cache.get(key);
  if (!hit) return null;
  if (Date.now() > hit.expires) {
    cache.delete(key);
    return null;
  }
  // Refresh recency for the crude LRU below.
  cache.delete(key);
  cache.set(key, hit);
  return hit.value;
}

function cacheSet(key, value) {
  if (cache.size >= CACHE_MAX) cache.delete(cache.keys().next().value);
  cache.set(key, { value, expires: Date.now() + CACHE_TTL_MS });
}

/** OSM `recycling:*` tags that indicate a site takes a given material family. */
const MATERIAL_TAGS = {
  plastic: ["plastic", "plastic_bottles", "plastic_packaging", "pet", "beverage_cartons"],
  paper: ["paper", "cardboard", "newspaper", "paper_packaging", "beverage_cartons"],
  glass: ["glass", "glass_bottles"],
  metal: ["cans", "scrap_metal", "aluminium", "metal", "beverage_cans"],
};

const EARTH_KM = 6371;

export function haversineKm(a, b) {
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLon = toRad(b.lon - a.lon);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 + Math.sin(dLon / 2) ** 2 * Math.cos(lat1) * Math.cos(lat2);
  return 2 * EARTH_KM * Math.asin(Math.sqrt(h));
}

// Three exact tag matches rather than a regex union: exact values can use
// Overpass's tag index, whereas `~"^(a|b|c)$"` forces a scan. The server-side
// [timeout:] sits under our own ceiling so Overpass gives up first and returns
// an answer rather than us cutting the connection.
function buildQuery(lat, lon, radius) {
  return `[out:json][timeout:10];
(
  nwr["amenity"="recycling"](around:${radius},${lat},${lon});
  nwr["amenity"="waste_disposal"](around:${radius},${lat},${lon});
  nwr["amenity"="waste_transfer_station"](around:${radius},${lat},${lon});
);
out center tags 40;`;
}

// Overpass is a free, shared, volunteer-run service. Its usage policy asks
// callers to identify themselves; requests without a User-Agent are rejected
// with HTTP 406. Set OVERPASS_USER_AGENT to your own contact in production.
const USER_AGENT =
  process.env.OVERPASS_USER_AGENT ?? "EcoScanAI/1.0 (waste sorting assistant)";

// Hard ceiling per attempt: the public instances queue under load, and a user
// waiting on disposal advice should get an empty list rather than a hang.
const REQUEST_TIMEOUT_MS = Number(process.env.OVERPASS_TIMEOUT_MS ?? 6000);

// Whole-lookup ceiling, and therefore the worst case the user waits. The public
// instances are slot-limited and their latency swings wildly, so this is kept
// deliberately tight: the advice is the point, and an empty facility list with
// an honest note beats a long spinner. Raise it if you run your own instance.
const TOTAL_BUDGET_MS = Number(process.env.OVERPASS_BUDGET_MS ?? 8000);

/**
 * @param {number} deadline epoch ms after which no further work may start.
 * Each fetch gets whichever is smaller: the per-request ceiling or whatever is
 * left of the overall budget. Without this the retry and mirror loops multiply
 * (2 mirrors x 2 attempts x 8s) and blow past the budget entirely.
 */
async function overpass(query, signal, deadline) {
  let lastError;
  const remaining = () => deadline - Date.now();

  for (const url of ENDPOINTS) {
    if (remaining() <= 0) break;
    // 429 (no free slot) and 504 (gateway busy) are Overpass saying "later",
    // not "no". One short backoff clears them most of the time.
    for (let attempt = 0; attempt < 2; attempt += 1) {
      const budget = Math.min(REQUEST_TIMEOUT_MS, remaining());
      if (budget <= 0) break;
      const timeout = AbortSignal.timeout(budget);
      // Abort if either the caller gives up or our own ceiling is reached.
      const composite = signal ? AbortSignal.any([signal, timeout]) : timeout;
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
            "User-Agent": USER_AGENT,
            Accept: "application/json",
          },
          body: new URLSearchParams({ data: query }),
          signal: composite,
        });
        if (res.status === 429 || res.status === 504) {
          lastError = new Error(`Overpass ${res.status}`);
          // Only worth backing off if there's budget left to use afterwards.
          if (attempt === 0 && remaining() > 1500 + 2000) {
            await sleep(1500);
            continue;
          }
          break;
        }
        if (!res.ok) throw new Error(`Overpass ${res.status}`);
        return await res.json();
      } catch (err) {
        // The caller cancelled; don't burn the remaining mirrors.
        if (signal?.aborted) throw err;
        lastError = err;
        break;
      }
    }
  }
  throw lastError ?? new Error("Overpass unreachable");
}

/** A readable description from tags alone - never a made-up proper name. */
function describe(tags) {
  if (tags.name) return { name: tags.name, named: true };
  if (tags.amenity === "waste_disposal") return { name: "Public waste disposal point", named: false };
  if (tags.amenity === "waste_transfer_station") return { name: "Waste transfer station", named: false };
  if (tags.recycling_type === "centre") return { name: "Recycling centre", named: false };
  return { name: "Recycling point", named: false };
}

function acceptedMaterials(tags) {
  return Object.entries(tags)
    .filter(([k, v]) => k.startsWith("recycling:") && (v === "yes" || v === "designated"))
    .map(([k]) => k.slice("recycling:".length));
}

function addressFrom(tags) {
  const parts = [
    [tags["addr:housenumber"], tags["addr:street"]].filter(Boolean).join(" "),
    tags["addr:suburb"] || tags["addr:neighbourhood"],
    tags["addr:city"],
    tags["addr:postcode"],
  ].filter(Boolean);
  return parts.length ? parts.join(", ") : null;
}

/**
 * @param {{lat:number, lon:number}} origin
 * @param {{material?: string, hazardous?: boolean, limit?: number, signal?: AbortSignal}} opts
 */
export async function findFacilities(origin, { material, hazardous = false, limit = 5, signal } = {}) {
  const key = cacheKey(origin, material, hazardous);
  const cached = cacheGet(key);
  if (cached) return { ...cached, cached: true };

  const wanted = MATERIAL_TAGS[material] ?? [];
  const deadline = Date.now() + TOTAL_BUDGET_MS;
  // "We looked and found nothing" and "we couldn't look" are different answers,
  // and the UI says different things about them. A wider search timing out must
  // not erase the fact that a narrower one completed.
  let searched = false;
  let lastRadius = null;

  for (const radius of RADII_M) {
    if (Date.now() > deadline) break;

    let data;
    try {
      data = await overpass(buildQuery(origin.lat, origin.lon, radius), signal, deadline);
    } catch {
      continue;
    }
    searched = true;
    lastRadius = radius;

    const seen = new Set();
    const rows = [];

    for (const el of data.elements ?? []) {
      const tags = el.tags ?? {};
      const lat = el.lat ?? el.center?.lat;
      const lon = el.lon ?? el.center?.lon;
      if (lat == null || lon == null) continue;

      const key = `${el.type}/${el.id}`;
      if (seen.has(key)) continue;
      seen.add(key);

      const accepts = acceptedMaterials(tags);
      const isCentre = tags.recycling_type === "centre" || tags.amenity !== "recycling";
      const matches = wanted.some((w) => accepts.includes(w));

      // A site that lists materials but not this one is the wrong destination.
      if (!hazardous && accepts.length > 0 && !matches) continue;
      // Hazardous waste needs a staffed centre, not a street container.
      if (hazardous && !isCentre) continue;

      const { name, named } = describe(tags);
      rows.push({
        id: key,
        name,
        named,
        kind: tags.amenity === "recycling" ? (isCentre ? "Recycling centre" : "Recycling point") : "Waste disposal",
        distanceKm: Math.round(haversineKm(origin, { lat, lon }) * 10) / 10,
        lat,
        lon,
        address: addressFrom(tags),
        openingHours: tags.opening_hours ?? null,
        phone: tags.phone ?? tags["contact:phone"] ?? null,
        operator: tags.operator ?? null,
        accepts,
        // Ranking only: an exact material match and a named site are more useful.
        rank: (matches ? 0 : 1) + (named ? 0 : 0.5),
        source: "OpenStreetMap",
        osmUrl: `https://www.openstreetmap.org/${el.type}/${el.id}`,
      });
    }

    if (rows.length) {
      rows.sort((a, b) => a.rank - b.rank || a.distanceKm - b.distanceKm);
      const result = {
        facilities: rows.slice(0, limit).map(({ rank, named, ...f }) => f),
        source: "OpenStreetMap",
        searchRadiusKm: radius / 1000,
      };
      cacheSet(key, result);
      return result;
    }
  }

  const empty = {
    facilities: [],
    source: "OpenStreetMap",
    error: searched ? null : "lookup_failed",
    searchRadiusKm: (lastRadius ?? RADII_M.at(-1)) / 1000,
  };
  // Cache a genuine "nothing here", but never a failure - that should retry.
  if (searched) cacheSet(key, empty);
  return empty;
}
